#!/usr/bin/env python3
"""
Second pass: translate remaining ~1590 keys using comprehensive
phrase-level dictionaries for Filipino and Ilocano.
"""

import re

TRANSLATIONS_JS = 'assets/js/translations.js'

def extract_lang_dict(content, lang):
    d = {}
    keys_order = []
    pattern = rf'^\s*{lang}:\s*\{{'
    lines = content.split('\n')
    in_block = False
    brace_depth = 0
    for line in lines:
        if not in_block:
            if re.match(pattern, line):
                in_block = True
                brace_depth = 1
                continue
        else:
            brace_depth += line.count('{') - line.count('}')
            if brace_depth <= 0:
                break
            m = re.match(r'\s*"([^"]+)":\s*"(.*)"', line)
            if m:
                key = m.group(1)
                val = m.group(2)
                if val.endswith('",'):
                    val = val[:-2]
                elif val.endswith(','):
                    val = val[:-1]
                d[key] = val
                keys_order.append(key)
    return d, keys_order

# ============================================================
# COMPREHENSIVE PHRASE DICTIONARIES - PASS 2
# Covers all remaining translatable content
# ============================================================

PASS2_FIL = {
    # Time/Duration - keep as-is but translate text parts
    "1 day": "1 araw",
    "1 hour": "1 oras",
    "1 hour 35 minutes": "1 oras 35 minuto",
    "1 hour 38 minutes": "1 oras 38 minuto",
    "1 hr 35-38 mins": "1 oras 35-38 minuto",
    "1 minute": "1 minuto",
    "1-2 Days": "1-2 Araw",
    "1-2 days": "1-2 araw",
    "1-2 weeks": "1-2 linggo",
    "1-2 weeks (posting required)": "1-2 linggo (kailangan ng pag-post)",
    "1-3 Days": "1-3 Araw",
    "1-3 days": "1-3 araw",
    "1-5 Days": "1-5 Araw",
    "10 Days": "10 Araw",
    "10 days (posting period)": "10 araw (panahon ng pag-post)",
    "10 days (posting)": "10 araw (pag-post)",
    "10 days, 5 hours and 10 minutes": "10 araw, 5 oras at 10 minuto",
    "10 min": "10 min",
    "10 mins": "10 min",
    "10 minutes": "10 minuto",
    "120 Days": "120 Araw",
    "120 days": "120 araw",
    "15 min": "15 min",
    "15 minutes": "15 minuto",
    "15-30 Days": "15-30 Araw",
    "15-30 Minutes": "15-30 Minuto",
    "15-30 min": "15-30 min",
    "15-30 minutes": "15-30 minuto",
    "2 minutes": "2 minuto",
    "2-3 days": "2-3 araw",
    "2-3 months": "2-3 buwan",
    "20 minutes": "20 minuto",
    "3 minutes": "3 minuto",
    "3-4 Years": "3-4 Taon",
    "3-4 months": "3-4 buwan",
    "3-5 Days": "3-5 Araw",
    "3-5 days": "3-5 araw",
    "3-6 months": "3-6 buwan",
    "30 min": "30 min",
    "30 minutes": "30 minuto",
    "30+ Days": "30+ Araw",
    "4 hours": "4 oras",
    "45 minutes": "45 minuto",
    "5 Minutes": "5 Minuto",
    "5 mins": "5 min",
    "5 minutes": "5 minuto",
    "5-10 Days": "5-10 Araw",
    "5-10 minutes": "5-10 minuto",
    "5-15 Days": "5-15 Araw",
    "5-7 Days": "5-7 Araw",
    "6 Months": "6 Buwan",
    "1 Year": "1 Taon",
    "8AM - 5PM": "8AM - 5PM",
    "8AM - 5PM (Mon-Fri)": "8AM - 5PM (Lun-Biy)",
    "6AM - 6PM": "6AM - 6PM",
    "4 PM": "4 PM",
    "fifteen (15) days": "labinlimang (15) araw",
    "thirty (30) days": "tatlumpung (30) araw",
    "Within 30 Days": "Sa Loob ng 30 Araw",

    # Quarters
    "1st Quarter": "Unang Quarter",
    "2nd Quarter": "Ikalawang Quarter",
    "3rd Quarter": "Ikatlong Quarter",
    "4th Quarter": "Ikaapat na Quarter",
    "Quarterly": "Quarterly",
    "Quarterly/Annual": "Quarterly/Taunang",
    "Q1": "Q1",
    "Q2": "Q2",
    "Jan - Mar": "Ene - Mar",
    "Apr - Jun": "Abr - Hun",

    # Dates
    "January 1-20": "Enero 1-20",
    "January 21 onwards": "Enero 21 pataas",
    "January 31": "Enero 31",
    "March 31": "Marso 31",
    "June 30": "Hunyo 30",
    "September 30": "Setyembre 30",
    "December 31": "Disyembre 31",
    "Last Updated: December 2, 2025": "Huling Na-update: Disyembre 2, 2025",

    # Government/Office titles
    "Office Head": "Pinuno ng Opisina",
    "Department Head": "Pinuno ng Kagawaran",
    "Section Chief": "Pinuno ng Seksyon",
    "Administrative Aide": "Katulong Pang-administrasyon",
    "Administrative Aide VI": "Katulong Pang-administrasyon VI",
    "Executive Assistant": "Ehekutibong Katulong",
    "SB Member": "Miyembro ng SB",
    "SK Federation President": "Pangulo ng Pederasyon ng SK",
    "Liga ng mga Barangay President": "Liga ng mga Barangay President",
    "Government Directory": "Direktoryo ng Pamahalaan",
    "Government Efficiency": "Kahusayan ng Pamahalaan",
    "Government Offices": "Mga Opisina ng Pamahalaan",
    "Government Structure": "Istruktura ng Pamahalaan",
    "Government Plate": "Plaka ng Pamahalaan",
    "Municipal Offices": "Mga Opisina ng Munisipyo",
    "Municipal Data": "Datos ng Munisipyo",
    "Municipal Accounting": "Accounting ng Munisipyo",
    "Municipal Engineering": "Inhinyeriya ng Munisipyo",
    "Responsible Offices": "Mga Responsableng Opisina",

    # Service categories
    "Business Permits": "Mga Permiso sa Negosyo",
    "Business Services": "Mga Serbisyo sa Negosyo",
    "Business Tax": "Buwis sa Negosyo",
    "Health Services": "Mga Serbisyo sa Kalusugan",
    "Health & Wellness": "Kalusugan at Kagalingan",
    "Health Monitoring": "Pagsubaybay sa Kalusugan",
    "Health & Sanitation, Finance Appropriation and Budget": "Kalusugan at Kalinisan, Paglalaan ng Pananalapi at Badyet",
    "Engineering Services": "Mga Serbisyo sa Inhinyeriya",
    "Engineering": "Inhinyeriya",
    "Procurement Services": "Mga Serbisyo sa Pagkuha",
    "Procurement Process": "Proseso ng Pagkuha",
    "Online Services": "Mga Online na Serbisyo",
    "Service Categories": "Mga Kategorya ng Serbisyo",
    "Service Description": "Paglalarawan ng Serbisyo",
    "Services Available": "Mga Serbisyong Magagamit",
    "Services Provided": "Mga Serbisyong Ibinibigay",
    "Slaughterhouse Services": "Mga Serbisyo ng Katayan",
    "Utility Services": "Mga Serbisyo sa Utilidad",
    "View Services": "Tingnan ang mga Serbisyo",
    "View Statistics": "Tingnan ang mga Estadistika",

    # Document types
    "Barangay Certificate": "Sertipiko ng Barangay",
    "Barangay Certification": "Sertipikasyon ng Barangay",
    "Barangay Business Clearance": "Business Clearance ng Barangay",
    "Barangay Budget": "Badyet ng Barangay",
    "Barangay Units": "Mga Yunit ng Barangay",
    "Barangay Health Workers": "Mga Manggagawang Pangkalusugan ng Barangay",
    "Barangay Affairs, Tourism": "Mga Usapin ng Barangay, Turismo",
    "CENOMAR": "CENOMAR",
    "Certified Payroll": "Sertipikadong Payroll",
    "Calamity Certification": "Sertipikasyon ng Kalamidad",
    "CLUP Certification": "Sertipikasyon ng CLUP",
    "Crop Certification": "Sertipikasyon ng Pananim",
    "Farm Location Certification": "Sertipikasyon ng Lokasyon ng Bukid",
    "Farmer Certification": "Sertipikasyon ng Magsasaka",
    "Planning Certification": "Sertipikasyon ng Pagpaplano",
    "Agricultural Certifications": "Mga Sertipikasyon sa Agrikultura",
    "Mayor's Clearance": "Clearance ng Alkalde",
    "Mayor's Clearance (Employment)": "Clearance ng Alkalde (Trabaho)",
    "Market Clearance": "Clearance ng Pamilihan",
    "NBI Clearance": "NBI Clearance",
    "NBI/Police Clearance": "NBI/Police Clearance",
    "Tax Clearance": "Tax Clearance",
    "Locational Clearance": "Locational Clearance",
    "Locational Clearance (if applicable)": "Locational Clearance (kung naaangkop)",
    "Zoning Clearance (Commercial)": "Zoning Clearance (Komersyal)",
    "Zoning Clearance (Residential)": "Zoning Clearance (Residensyal)",
    "Zoning Clearance from MPDO": "Zoning Clearance mula sa MPDO",
    "Corporate Cedula": "Corporate Cedula",
    "Individual Cedula": "Indibidwal na Cedula",
    "Service Record": "Rekord ng Serbisyo",
    "Financial Report": "Ulat Pinansyal",
    "Financial Statements (for corporations)": "Mga Pahayag Pinansyal (para sa mga korporasyon)",
    "Financial Transparency": "Transparency sa Pananalapi",
    "Trial Balance": "Trial Balance",
    "Legislative Documents": "Mga Dokumentong Lehislatibo",
    "Ordinances": "Mga Ordinansa",
    "Resolutions": "Mga Resolusyon",
    "Documentary Requirements": "Mga Kinakailangang Dokumento",
    "Required Documents": "Mga Kinakailangang Dokumento",
    "Supporting Documents": "Mga Suportang Dokumento",
    "Document Type": "Uri ng Dokumento",
    "Document Owner": "May-ari ng Dokumento",
    "Legal Basis": "Legal na Batayan",
    "Legal Assistance": "Tulong Legal",
    "Legal": "Legal",
    "Obligation Request": "Kahilingan ng Obligasyon",
    "Obligation Request (ObR)": "Kahilingan ng Obligasyon (ObR)",
    "Purchase Request/Order": "Kahilingan/Order ng Pagbili",
    "Transport Permit": "Permiso sa Transportasyon",
    "Delivery Permit": "Permiso sa Paghahatid",
    "Development Permit": "Permiso sa Pagpapaunlad",
    "Sign Permit": "Permiso sa Karatula",
    "Special Permit (Events)": "Espesyal na Permiso (Mga Kaganapan)",
    "Electronics Permit": "Permiso sa Elektroniks",
    "Installation Permit (if applicable)": "Permiso sa Pag-install (kung naaangkop)",
    "Other Permits": "Iba pang Permiso",
    "Permit Processing": "Pagproseso ng Permiso",
    "Permit Renewal": "Pag-renew ng Permiso",
    "Permit Type": "Uri ng Permiso",
}

PASS2_FIL_2 = {
    # Process/Action terms
    "About AICS": "Tungkol sa AICS",
    "About CENOMAR": "Tungkol sa CENOMAR",
    "About Corrections": "Tungkol sa mga Pagwawasto",
    "About Procurement": "Tungkol sa Pagkuha",
    "About SEA-K Program": "Tungkol sa Programa ng SEA-K",
    "About SLP": "Tungkol sa SLP",
    "About Social Pension": "Tungkol sa Social Pension",
    "About Vehicle Rental": "Tungkol sa Pag-upa ng Sasakyan",
    "About the Feeding Program": "Tungkol sa Programa ng Pagpapakain",
    "After Validation": "Pagkatapos ng Pagpapatunay",
    "After deadline": "Pagkatapos ng deadline",
    "Answer questions for encoding": "Sagutin ang mga tanong para sa pag-encode",
    "Assign ObR Number": "Magtalaga ng Numero ng ObR",
    "Assign account Code": "Magtalaga ng Code ng Account",
    "Attend the PMC": "Dumalo sa PMC",
    "Authentication/Verification": "Pagpapatunay/Beripikasyon",
    "By Application": "Sa pamamagitan ng Aplikasyon",
    "By Schedule": "Ayon sa Iskedyul",
    "Cash Ticket Issuance": "Pagbibigay ng Cash Ticket",
    "Check Issuance": "Pagbibigay ng Tseke",
    "Client Feedback": "Puna ng Kliyente",
    "Client/End-User": "Kliyente/End-User",
    "Closure of Business": "Pagsasara ng Negosyo",
    "Committee Report": "Ulat ng Komite",
    "Consent:": "Pahintulot:",
    "Contents": "Mga Nilalaman",
    "Create Account": "Gumawa ng Account",
    "Deadline": "Deadline",
    "Duplicate Copy": "Duplikadong Kopya",
    "Effectivity Quarter and Year": "Quarter at Taon ng Bisa",
    "Eligibility Criteria": "Mga Pamantayan ng Pagiging Karapat-dapat",
    "Eligible Beneficiaries": "Mga Karapat-dapat na Benepisyaryo",
    "Emergency": "Emergency",
    "Emergency Hotlines": "Mga Emergency Hotline",
    "Emergency cases are given priority": "Ang mga kaso ng emergency ay binibigyan ng prayoridad",
    "Encoding and processing of PWD ID": "Pag-encode at pagproseso ng PWD ID",
    "Enrollment Requirements": "Mga Kinakailangan sa Pagpapatala",
    "Entrance Fees": "Mga Bayad sa Pagpasok",
    "Entry Management": "Pamamahala ng Pagpasok",
    "Equipment": "Kagamitan",
    "Equipment accountability is strictly enforced": "Ang pananagutan sa kagamitan ay mahigpit na ipinapatupad",
    "Error-free or uninterrupted": "Walang error o walang pagkaantala",
    "Essential Cookies:": "Mga Mahahalagang Cookie:",
    "Exercising Your Rights": "Paggamit ng Iyong mga Karapatan",
    "Expiry Note": "Paalala sa Pag-expire",
    "External References": "Mga Panlabas na Sanggunian",
    "External Resources": "Mga Panlabas na Mapagkukunan",
    "Facebook Page": "Pahina sa Facebook",
    "Facility Maintenance": "Pagpapanatili ng Pasilidad",
    "Fee Collection": "Koleksyon ng Bayad",
    "Fee Range": "Saklaw ng Bayad",
    "Fee Schedule": "Iskedyul ng Bayad",
    "Fee Summary": "Buod ng Bayad",
    "Filing Fee": "Bayad sa Paghahain",
    "Final Draft Printing": "Pag-print ng Huling Draft",
    "Finance": "Pananalapi",
    "For Employment": "Para sa Trabaho",
    "For Machinery Declaration": "Para sa Deklarasyon ng Makinarya",
    "For Ordinances": "Para sa mga Ordinansa",
    "For Resolutions": "Para sa mga Resolusyon",
    "For illness or medical reasons": "Para sa sakit o medikal na dahilan",
    "For personal matters, rest, and recreation": "Para sa personal na usapin, pahinga, at libangan",
    "For:": "Para sa:",
    "Franchise Steps": "Mga Hakbang sa Prangkisa",
    "Franchising": "Prangkisa",
    "Free/Subsidized": "Libre/Subsidyado",
    "General Requirements": "Mga Pangkalahatang Kinakailangan",
    "Basic Requirements": "Mga Pangunahing Kinakailangan",
    "Additional Requirements (If Applicable)": "Mga Karagdagang Kinakailangan (Kung Naaangkop)",
    "Getting Married": "Pagpapakasal",
    "Got in Trouble": "Nagkaproblema",
    "Growth": "Paglago",
    "Growth Monitoring": "Pagsubaybay sa Paglago",
    "HR Management": "Pamamahala ng HR",
    "Heavy Duty": "Mabigat na Trabaho",
    "Heavy Equipment": "Mabigat na Kagamitan",
    "Higher Education": "Mas Mataas na Edukasyon",
    "Important Information": "Mahalagang Impormasyon",
    "Important Note": "Mahalagang Paalala",
    "Improved": "Pinahusay",
    "Implementation": "Pagpapatupad",
    "Implementation of intervention/assistance": "Pagpapatupad ng interbensyon/tulong",
    "Inclusion in Session Agenda": "Pagsasama sa Agenda ng Sesyon",
    "Income and Expenditure Estimates": "Mga Tantiya ng Kita at Gastusin",
    "Indemnification": "Pagbabayad-pinsala",
    "Indigent": "Indigente",
    "Industry": "Industriya",
    "Infrastructure & Development": "Imprastraktura at Pagpapaunlad",
    "Innovation": "Inobasyon",
    "Inspection Committee": "Komite ng Inspeksyon",
    "Insurance coverage for aquaculture operations": "Saklaw ng seguro para sa mga operasyon ng akwakultura",
    "Insurance coverage for rice crops against natural calamities": "Saklaw ng seguro para sa mga pananim na bigas laban sa mga natural na kalamidad",
    "Item Type": "Uri ng Aytem",
    "Kind of Machinery": "Uri ng Makinarya",
    "Land Declaration": "Deklarasyon ng Lupa",
    "Land Reclassification": "Reklasipikasyon ng Lupa",
    "Late Payment": "Huling Pagbabayad",
    "Leave Application": "Aplikasyon ng Leave",
    "Leave Credits": "Mga Kredito ng Leave",
    "Leave Processing": "Pagproseso ng Leave",
    "Leave Type": "Uri ng Leave",
    "License Validity": "Bisa ng Lisensya",
    "License Waiting": "Paghihintay ng Lisensya",
    "Licensing Officer": "Opisyal ng Lisensya",
    "Light Vehicle": "Magaan na Sasakyan",
    "Light Vehicles": "Mga Magaan na Sasakyan",
    "List of activities/program": "Listahan ng mga aktibidad/programa",
    "Livelihood": "Kabuhayan",
    "Livestock": "Mga Hayop",
    "Livestock Program": "Programa ng Livestock",
    "Livestock Registration": "Pagpaparehistro ng Livestock",
    "Livestock Training": "Pagsasanay sa Livestock",
    "Loading news...": "Naglo-load ng balita...",
    "Loading updates...": "Naglo-load ng mga update...",
    "Loan Amount": "Halaga ng Pautang",
    "Low Interest": "Mababang Interes",
    "Low-Income": "Mababang Kita",
    "Lunch Break": "Tanghalian",
    "Main Navigation": "Pangunahing Nabigasyon",
    "Maintenance": "Pagpapanatili",
    "Maintenance Staff": "Kawani ng Pagpapanatili",
    "Managing Cookies": "Pamamahala ng mga Cookie",
    "Market Access": "Access sa Pamilihan",
    "Market Collector": "Kolektor ng Pamilihan",
    "Market Inspector": "Inspektor ng Pamilihan",
    "Market Linkage": "Koneksyon sa Pamilihan",
    "Market Operations": "Mga Operasyon ng Pamilihan",
    "Market Supervisor": "Superbisor ng Pamilihan",
    "Marriage Registration": "Pagpaparehistro ng Kasal",
    "Marriage/Corrections": "Kasal/Mga Pagwawasto",
    "Maternity Leave": "Maternity Leave",
    "Paternity Leave": "Paternity Leave",
    "Sick Leave": "Sick Leave",
    "Vacation Leave": "Vacation Leave",
    "Special Leave": "Espesyal na Leave",
    "Medical": "Medikal",
    "Medical Emergency Hotlines": "Mga Medikal na Emergency Hotline",
    "Medium": "Katamtaman",
    "Menu": "Menu",
    "Mobile": "Mobile",
    "Modifications": "Mga Pagbabago",
    "Multiple Units": "Maramihang Yunit",
    "Mun. Accounting": "Mun. Accounting",
    "Mun. Agriculture": "Mun. Agrikultura",
    "Mun. Budget": "Mun. Badyet",
    "Mun. Engineering": "Mun. Inhinyeriya",
    "Navigation": "Nabigasyon",
    "Net Operating Income": "Netong Kita sa Operasyon",
    "New Owner": "Bagong May-ari",
    "News & Updates": "Balita at mga Update",
    "No Professional Advice": "Walang Propesyonal na Payo",
    "No Surcharge": "Walang Karagdagang Singil",
    "No discount/penalty": "Walang diskwento/multa",
    "Nutrition Education": "Edukasyon sa Nutrisyon",
    "Official Signing": "Opisyal na Pagpirma",
    "Offline": "Offline",
    "On Request": "Sa Kahilingan",
    "Online": "Online",
    "Operations Management": "Pamamahala ng Operasyon",
    "Operator": "Operator",
    "Operators Pool": "Pool ng mga Operator",
    "Organic Agriculture": "Organikong Agrikultura",
    "Organic Agriculture Program": "Programa ng Organikong Agrikultura",
    "Organic Farming Training": "Pagsasanay sa Organikong Pagsasaka",
    "Organic Inputs": "Mga Organikong Input",
    "Organic Seeds": "Mga Organikong Binhi",
    "Output": "Output",
    "Owner Information": "Impormasyon ng May-ari",
    "Owner/Creditor": "May-ari/Pinagkakautangan",
    "Owner/Relative": "May-ari/Kamag-anak",
    "Owner/Rep": "May-ari/Kinatawan",
    "Payment Details": "Detalye ng Pagbabayad",
    "Payment Period": "Panahon ng Pagbabayad",
    "Payment Processing": "Pagproseso ng Pagbabayad",
    "Payment Schedule": "Iskedyul ng Pagbabayad",
    "Payout": "Pagbabayad",
    "Payroll Preparation": "Paghahanda ng Payroll",
    "Payroll Register": "Rehistro ng Payroll",
    "Per Application": "Bawat Aplikasyon",
    "Per Cropping": "Bawat Pag-aani",
    "Per MTO": "Bawat MTO",
    "Per Requirement": "Bawat Kinakailangan",
    "Per Schedule": "Ayon sa Iskedyul",
    "Person Responsible": "Taong Responsable",
    "Phone/Hotline": "Telepono/Hotline",
    "Popular:": "Sikat:",
    "Posting / Publication": "Pag-post / Publikasyon",
    "Posting / Transmittal": "Pag-post / Transmittal",
    "Poverty": "Kahirapan",
    "Pre-Audit Disbursements": "Pre-Audit ng mga Disbursement",
    "Pre-Audit of Disbursement Vouchers": "Pre-Audit ng mga Disbursement Voucher",
    "Prenatal Care": "Pangangalaga Bago Manganak",
    "Primary & Elementary": "Primarya at Elementarya",
    "Process Flow": "Daloy ng Proseso",
    "Processing & Certification": "Pagproseso at Sertipikasyon",
    "Processing times may vary based on workload": "Ang oras ng pagproseso ay maaaring mag-iba batay sa dami ng trabaho",
    "Processing:": "Pagproseso:",
    "Program Components": "Mga Bahagi ng Programa",
    "Program Features": "Mga Tampok ng Programa",
    "Program Tracks": "Mga Track ng Programa",
    "Project Monitoring": "Pagsubaybay sa Proyekto",
    "Property Custodian": "Tagapag-ingat ng Ari-arian",
    "Property Custodianship": "Pag-iingat ng Ari-arian",
    "Property Inspection": "Inspeksyon ng Ari-arian",
    "Property Location": "Lokasyon ng Ari-arian",
    "Property Management": "Pamamahala ng Ari-arian",
    "Property Owner": "May-ari ng Ari-arian",
    "Protection of Rights:": "Proteksyon ng mga Karapatan:",
    "Protective Services": "Mga Serbisyong Proteksiyon",
    "Public Hearing / Committee Action": "Pagdinig Publiko / Aksyon ng Komite",
    "Public Participation": "Pakikilahok ng Publiko",
    "Public Works": "Mga Pampublikong Gawa",
    "Purpose of Certification": "Layunin ng Sertipikasyon",
    "Purpose of travel/use": "Layunin ng paglalakbay/paggamit",
    "Receiving & Sorting": "Pagtanggap at Pag-aayos",
    "Receiving Application Form": "Pagtanggap ng Application Form",
    "Receiving Clerk": "Klerk ng Pagtanggap",
    "Reclassification": "Reklasipikasyon",
    "Records Request": "Kahilingan ng mga Rekord",
    "Records Section": "Seksyon ng mga Rekord",
    "Records Steps": "Mga Hakbang sa Rekord",
    "Records/Clerical": "Mga Rekord/Klerikal",
    "Recycling Program": "Programa ng Pag-recycle",
    "Referral to appropriate agencies (if needed)": "Referral sa naaangkop na ahensya (kung kinakailangan)",
    "Referred Clients": "Mga Na-refer na Kliyente",
    "Registration Officer": "Opisyal ng Pagpaparehistro",
    "Regulatory Fees": "Mga Bayad sa Regulasyon",
    "Rehabilitation": "Rehabilitasyon",
    "Rehabilitation Services": "Mga Serbisyo ng Rehabilitasyon",
    "Releasing & Stamping": "Paglabas at Pagtatak",
    "Renewal Period": "Panahon ng Pag-renew",
    "Rental Process": "Proseso ng Pag-upa",
    "Rental Rate": "Rate ng Pag-upa",
    "Resiliency": "Katatagan",
    "Scheduled": "Naka-iskedyul",
    "Second Reading": "Ikalawang Pagbasa",
    "Self-Employment": "Sariling Negosyo",
    "Self-drive": "Sariling pagmamaneho",
    "Self-operate": "Sariling pagpapatakbo",
    "Senior Citizens": "Mga Matatandang Mamamayan",
    "Server Logs:": "Mga Log ng Server:",
    "Severability": "Pagkakahiwalay",
    "Slaughter Fee": "Bayad sa Pagkatay",
    "Slaughter Operations": "Mga Operasyon ng Pagkatay",
    "Slaughter of Carabao": "Pagkatay ng Kalabaw",
    "Slaughter of Cattle": "Pagkatay ng Baka",
    "Slaughter of Goat": "Pagkatay ng Kambing",
    "Slaughter of Hog": "Pagkatay ng Baboy",
    "Slaughter of carabao": "Pagkatay ng kalabaw",
    "Slaughter of cattle": "Pagkatay ng baka",
    "Slaughter of goat": "Pagkatay ng kambing",
    "Slaughter of hog": "Pagkatay ng baboy",
    "Slaughterhouse Supervisor": "Superbisor ng Katayan",
    "Social Case Study": "Pag-aaral ng Kaso sa Lipunan",
    "Social Pension": "Social Pension",
    "Social Welfare Assistant": "Katulong sa Kagawaran ng Kapakanan",
    "Social Worker": "Social Worker",
    "Socialization": "Pakikisalamuha",
    "Solid Waste Management": "Pamamahala ng Solidong Basura",
    "Source Links and External References": "Mga Link ng Pinagmulan at Panlabas na Sanggunian",
    "Starting a Business": "Pagsisimula ng Negosyo",
    "Stay informed about the latest happenings in Solano": "Manatiling may kaalaman tungkol sa mga pinakabagong pangyayari sa Solano",
    "Storekeeper": "Tagapag-ingat ng Bodega",
    "Submit Documents": "Isumite ang mga Dokumento",
    "Subsidized": "Subsidyado",
    "Supplies Procurement": "Pagkuha ng mga Suplay",
    "Supply Officer": "Opisyal ng Suplay",
    "Target": "Target",
    "Technical Training": "Teknikal na Pagsasanay",
    "Telephone": "Telepono",
    "Temporary Shelter": "Pansamantalang Tirahan",
    "Third-Party Links": "Mga Link ng Third-Party",
    "Time Frame": "Takdang Panahon",
    "Timely Registration": "Napapanahong Pagpaparehistro",
    "Tips": "Mga Tip",
    "Total Expenditures": "Kabuuang Gastusin",
    "Total Fees": "Kabuuang Bayad",
    "Total Income": "Kabuuang Kita",
    "Total Processing": "Kabuuang Pagproseso",
    "Track": "Track",
    "Transportation Assistance": "Tulong sa Transportasyon",
    "Treasury": "Ingat-Yaman",
    "Type of Clearance": "Uri ng Clearance",
    "Type of Work": "Uri ng Trabaho",
    "Types of Annotations": "Mga Uri ng Anotasyon",
    "Types of Corrections": "Mga Uri ng Pagwawasto",
    "Updated Ledgers": "Na-update na mga Ledger",
    "Upon Approval": "Sa Pag-apruba",
    "Urban Planning": "Pagpaplano ng Lungsod",
    "Utility Management Functions": "Mga Tungkulin sa Pamamahala ng Utilidad",
    "Utility Worker": "Utility Worker",
    "Utility Workers": "Mga Utility Worker",
    "Valid Coverage": "Balidong Saklaw",
    "Valid Passport": "Balidong Pasaporte",
    "Validity:": "Bisa:",
    "Varies by Business": "Nag-iiba ayon sa Negosyo",
    "Vehicle & Equipment": "Sasakyan at Kagamitan",
    "Vehicle Rental": "Pag-upa ng Sasakyan",
    "Vehicle Type": "Uri ng Sasakyan",
    "Vehicles": "Mga Sasakyan",
    "Visual": "Biswal",
    "Walk-in": "Walk-in",
    "Water": "Tubig",
    "Weight Range": "Saklaw ng Timbang",
    "What to Do": "Ano ang Gagawin",
    "Your Rights": "Ang Iyong mga Karapatan",
    "not": "hindi",
    "transparency": "transparency",
    "via Filipizen": "sa pamamagitan ng Filipizen",
    "Appointment": "Appointment",
    "Email": "Email",
    "Email Address": "Email Address",
    "Hotline": "Hotline",
    "Error": "Error",
    "OK": "OK",
    "Accounting": "Accounting",
}

PASS2_FIL_3 = {
    # Welfare/Social services
    "Aftercare Services": "Mga Serbisyo Pagkatapos ng Pangangalaga",
    "Children's Welfare": "Kagalingan ng mga Bata",
    "Women's Welfare": "Kagalingan ng mga Kababaihan",
    "Counseling Services": "Mga Serbisyo ng Pagpapayo",
    "Crisis Intervention": "Interbensyon sa Krisis",
    "Day Care": "Day Care",
    "Day Care Worker": "Manggagawa ng Day Care",
    "Disaster Assistance": "Tulong sa Sakuna",
    "Early Learning": "Maagang Pagkatuto",
    "Family Reintegration": "Muling Pagsasama ng Pamilya",
    "Feeding": "Pagpapakain",
    "Hot Meals": "Mainit na Pagkain",
    "Immediate Family": "Kagyat na Pamilya",
    "Psychosocial Rehabilitation": "Psychosocial na Rehabilitasyon",
    "Rehabilitation / Major Repair of Flood Control Structure": "Rehabilitasyon / Malaking Pagkukumpuni ng Istruktura ng Flood Control",
    "Supplemental feeding program": "Programa ng karagdagang pagpapakain",
    "Supplementary Feeding Program": "Programa ng Karagdagang Pagpapakain",
    "Beneficiaries": "Mga Benepisyaryo",
    "4Ps Members": "Mga Miyembro ng 4Ps",
    "Victims of abuse, neglect, and exploitation": "Mga biktima ng pang-aabuso, kapabayaan, at pagsasamantala",
    "Victims of trafficking": "Mga biktima ng trafficking",
    "Persons with disabilities (PWDs)": "Mga taong may kapansanan (PWDs)",
    "Frail, sickly, or with disability": "Mahina, sakitin, o may kapansanan",

    # Agriculture
    "Aquaculture Inputs": "Mga Input sa Akwakultura",
    "Artificial Insemination": "Artipisyal na Inseminasyon",
    "Corn Seeds Distribution": "Pamamahagi ng mga Binhi ng Mais",
    "Credit Assistance": "Tulong sa Kredito",
    "DA Programs": "Mga Programa ng DA",
    "Dispersal Program": "Programa ng Pamamahagi",
    "Distribution": "Pamamahagi",
    "Farmers Field School": "Paaralan sa Bukid ng mga Magsasaka",
    "Farmers Organization": "Organisasyon ng mga Magsasaka",
    "Fertilizer Support": "Suporta sa Pataba",
    "Fingerlings Distribution": "Pamamahagi ng mga Fingerling",
    "Fisherfolk Registration": "Pagpaparehistro ng mga Mangingisda",
    "Fishery Insurance": "Seguro sa Pangingisda",
    "Fishery Program": "Programa sa Pangingisda",
    "Fishing Equipment": "Kagamitan sa Pangingisda",
    "Mechanization Support": "Suporta sa Mekanisasyon",
    "Post-Harvest Facilities": "Mga Pasilidad Pagkatapos ng Ani",
    "RSBSA Registration": "Pagpaparehistro sa RSBSA",
    "RSBSA Registration (Farm Registration)": "Pagpaparehistro sa RSBSA (Pagpaparehistro ng Bukid)",
    "RSBSA Registration (if applicable)": "Pagpaparehistro sa RSBSA (kung naaangkop)",
    "Skills Training": "Pagsasanay sa Kasanayan",
    "Skills Dev't": "Pagpapaunlad ng Kasanayan",

    # Engineering/Infrastructure
    "Architectural Plans": "Mga Plano ng Arkitektura",
    "Electrical Plans": "Mga Plano ng Elektrikal",
    "Electronics Plans": "Mga Plano ng Elektroniks",
    "Plumbing Plans": "Mga Plano ng Plumbing",
    "Sanitary Plans": "Mga Plano ng Sanitaryo",
    "Structural Plans": "Mga Plano ng Istruktura",
    "Building Declaration": "Deklarasyon ng Gusali",
    "Machinery Declaration": "Deklarasyon ng Makinarya",
    "Drainage & Sewerage Management": "Pamamahala ng Drainage at Alkantarilya",
    "Flood Control": "Flood Control",
    "Flood Control & Mitigation": "Flood Control at Pagpapagaan",
    "Road Grader": "Road Grader",
    "Road Roller": "Road Roller",
    "Backhoe Loader": "Backhoe Loader",
    "Compactor": "Compactor",
    "Dump Truck": "Dump Truck",
    "Dump Truck Driver": "Driver ng Dump Truck",
    "Dump Truck Operations": "Mga Operasyon ng Dump Truck",
    "Generator Set": "Generator Set",
    "Grass Cutter": "Grass Cutter",
    "Water Truck": "Water Truck",
    "Motorcycle": "Motorsiklo",
    "Motorcycles": "Mga Motorsiklo",
    "Available Equipment": "Mga Magagamit na Kagamitan",
    "Available Vehicles": "Mga Magagamit na Sasakyan",
    "Assigned Driver": "Nakatalagang Driver",
    "Assigned Operator": "Nakatalagang Operator",
    "Assignment": "Pagtatalaga",
    "Authorized driver assignment": "Awtorisadong pagtatalaga ng driver",
    "Contractor": "Kontratista",
    "Contract Cost": "Gastos ng Kontrata",
    "Construction of Flood Mitigation Structure": "Pagtatayo ng Istruktura ng Pagpapagaan ng Baha",
    "Structural Type and Materials": "Uri ng Istruktura at mga Materyales",

    # Market/Slaughterhouse
    "Butcher": "Magkakatay",
    "Collection Officer": "Opisyal ng Koleksyon",
    "Dry Goods": "Mga Tuyong Paninda",
    "Fish & Seafood": "Isda at Pagkaing-dagat",
    "Meat & Poultry": "Karne at Manok",
    "Meat Inspector": "Inspektor ng Karne",
    "Other Merchandise": "Iba pang Paninda",
    "Vegetables & Fruits": "Mga Gulay at Prutas",
    "Ticket Seller": "Tagabenta ng Tiket",
    "Gate Keeper": "Bantay ng Gate",

    # Legislative
    "Browse Ordinances": "Mag-browse ng mga Ordinansa",
    "Flowchart for Legislative Proposal": "Flowchart para sa Panukalang Lehislatibo",
    "Ordinances and resolutions of the Sangguniang Bayan ng Solano": "Mga ordinansa at resolusyon ng Sangguniang Bayan ng Solano",

    # Statistics/Data
    "Competitiveness": "Kompetitibidad",
    "Economic Dynamism": "Dinamismo ng Ekonomiya",
    "Economic Dynamism Trend": "Trend ng Dinamismo ng Ekonomiya",
    "Economic Services": "Mga Serbisyong Pang-ekonomiya",
    "Economy": "Ekonomiya",
    "Historical growth from 1990 to 2024": "Makasaysayang paglago mula 1990 hanggang 2024",
    "Infrastructure Trend": "Trend ng Imprastraktura",
    "Innovation Trend": "Trend ng Inobasyon",
    "IRA Dependency": "Pagdepende sa IRA",
    "Key Indicators Trend (2016-2024)": "Trend ng mga Pangunahing Tagapagpahiwatig (2016-2024)",
    "Population Bar Chart": "Bar Chart ng Populasyon",
    "Resiliency Trend": "Trend ng Katatagan",
    "Solano Competitive Index": "Competitive Index ng Solano",
    "Solano at a Glance": "Solano sa Isang Tingin",
    "Brief History of Solano": "Maikling Kasaysayan ng Solano",
    "22 Barangays": "22 Barangay",
    "24/7 Operations": "24/7 Operasyon",
    "60 Years+": "60 Taon+",
    "Nationwide": "Buong Bansa",

    # Privacy/Terms/Legal
    "Cookies & Analytics": "Mga Cookie at Analytics",
    "Content Concerns": "Mga Alalahanin sa Nilalaman",
    "Data Sharing": "Pagbabahagi ng Datos",
    "Disabling cookies may affect some website functionality": "Ang pag-disable ng mga cookie ay maaaring makaapekto sa ilang functionality ng website",
    "Legal Obligation:": "Legal na Obligasyon:",
    "Material changes may be announced on our website": "Ang mga mahahalagang pagbabago ay maaaring ianunsyo sa aming website",
    "No Professional Advice": "Walang Propesyonal na Payo",
    "Warranties of merchantability": "Mga garantiya ng kakayahang ibenta",
    "Fitness for a particular purpose": "Angkop para sa isang partikular na layunin",
    "Any interruption, suspension, or cessation of website availability": "Anumang pagkaantala, pagsuspinde, o pagtigil ng availability ng website",
    "If you believe that any content on this website is:": "Kung naniniwala ka na ang anumang nilalaman sa website na ito ay:",
    "In violation of applicable laws or regulations": "Lumalabag sa mga naaangkop na batas o regulasyon",
    "Infringing upon legitimate rights or interests": "Lumalabag sa mga lehitimong karapatan o interes",
    "Potentially harmful or dangerous": "Posibleng nakakapinsala o mapanganib",
    "You are strongly encouraged to:": "Lubos kang hinihikayat na:",
    "You can disable cookies through your browser settings": "Maaari mong i-disable ang mga cookie sa pamamagitan ng mga setting ng iyong browser",
    "Supporting documentation or evidence, where applicable": "Mga suportang dokumento o ebidensya, kung naaangkop",
    "Fully compatible with all devices, browsers, or assistive technologies": "Ganap na tugma sa lahat ng device, browser, o assistive technology",
    "Is this website mobile-friendly?": "Ang website ba na ito ay mobile-friendly?",
    "Who developed Better Solano?": "Sino ang gumawa ng Better Solano?",
    "What if I missed the registration deadline?": "Paano kung napalampas ko ang deadline ng pagpaparehistro?",
    "Select the scenario that applies to your situation": "Piliin ang senaryo na naaangkop sa iyong sitwasyon",
    "Response times may vary due to the volunteer nature of this initiative.": "Ang oras ng pagtugon ay maaaring mag-iba dahil sa boluntaryong katangian ng inisyatibang ito.",
    "Fetching news and updates from Solano.": "Kinukuha ang mga balita at update mula sa Solano.",
    "Fetching the latest news from Solano.": "Kinukuha ang pinakabagong balita mula sa Solano.",
    "Stay informed about the latest happenings in Solano": "Manatiling may kaalaman tungkol sa mga pinakabagong pangyayari sa Solano",
    "Number of visitors and page views": "Bilang ng mga bisita at page view",
    "Browser type and version": "Uri at bersyon ng browser",
    "Device type and operating system": "Uri ng device at operating system",
    "Geographic location (country/city level)": "Heograpikong lokasyon (antas ng bansa/lungsod)",
    "Pages visited and time spent on pages": "Mga pahinang binisita at oras na ginugol sa mga pahina",
    "Traffic sources and user flow": "Mga pinagmulan ng trapiko at daloy ng gumagamit",
    "Referring website or source": "Pinanggalingang website o pinagmulan",
    "IP address (anonymized where possible)": "IP address (anonymized kung maaari)",
    "Name (if provided in correspondence)": "Pangalan (kung ibinigay sa sulat)",
    "To analyze website traffic and usage patterns": "Upang suriin ang trapiko ng website at mga pattern ng paggamit",
    "To improve website functionality and user experience": "Upang mapabuti ang functionality ng website at karanasan ng gumagamit",
    "Regular security assessments": "Regular na pagtatasa ng seguridad",
    "Regular software updates and patches": "Regular na pag-update at pag-patch ng software",
    "Google Analytics Opt-out Browser Add-on": "Google Analytics Opt-out Browser Add-on",
    "Schedule Appointment": "Mag-iskedyul ng Appointment",
}

PASS2_FIL_4 = {
    # Specific long sentences from service pages
    "Certification by the MBO of the availability of appropriation and allotment": "Sertipikasyon ng MBO ng pagkakaroon ng appropriasyon at allotment",
    "Certification for crop damage due to natural calamities": "Sertipikasyon para sa pinsala sa pananim dahil sa mga natural na kalamidad",
    "Certification that individual is a registered farmer in Solano": "Sertipikasyon na ang indibidwal ay isang rehistradong magsasaka sa Solano",
    "Checking/validating of the availability of appropriation and allotment from the Status of Appropriation, Allotment, Obligation (SAOB)": "Pagsusuri/pagpapatunay ng pagkakaroon ng appropriasyon at allotment mula sa Status of Appropriation, Allotment, Obligation (SAOB)",
    "Cities and Municipalities Competitiveness Index (CMCI) Performance 2016-2024": "Pagganap ng Cities and Municipalities Competitiveness Index (CMCI) 2016-2024",
    "Classification (Agricultural, Commercial, Industrial, Residential)": "Klasipikasyon (Agrikultural, Komersyal, Industriyal, Residensyal)",
    "Clerical Error Correction (RA 9048)": "Pagwawasto ng Klerikal na Error (RA 9048)",
    "Consolidated PRs, APP": "Pinagsama-samang mga PR, APP",
    "Coordination with utility providers": "Koordinasyon sa mga tagapagbigay ng utilidad",
    "Correction of Sex (RA 10172)": "Pagwawasto ng Kasarian (RA 10172)",
    "Corrections": "Mga Pagwawasto",
    "Corrections & Annotations": "Mga Pagwawasto at Anotasyon",
    "Corrections and Amendments": "Mga Pagwawasto at Amyenda",
    "Corrections and Annotations": "Mga Pagwawasto at Anotasyon",
    "Counseling and therapy sessions for emotional and mental recovery.": "Mga sesyon ng pagpapayo at therapy para sa emosyonal at mental na pagbawi.",
    "DTI Registration (for sole proprietorship) or SEC Registration (for corporation)": "DTI Registration (para sa sole proprietorship) o SEC Registration (para sa korporasyon)",
    "DTI/SEC Registration": "DTI/SEC Registration",
    "Declaration must be filed within 60 days of acquisition": "Ang deklarasyon ay dapat ihain sa loob ng 60 araw mula sa pagkuha",
    "Declogging drainage, clearing waterways, and rehabilitating canals with MDRRMO collaboration.": "Pag-declog ng drainage, paglilinis ng mga daluyan ng tubig, at rehabilitasyon ng mga kanal sa pakikipagtulungan ng MDRRMO.",
    "Decree of Annulment (if annulled)": "Decree of Annulment (kung na-annul)",
    "Decree of Divorce (if divorced abroad)": "Decree of Divorce (kung nagdiborsiyo sa ibang bansa)",
    "Destination and estimated duration": "Destinasyon at tinatayang tagal",
    "Development planning, project monitoring, zoning": "Pagpaplano ng pagpapaunlad, pagsubaybay sa proyekto, zoning",
    "Disaster preparedness, emergency response, risk reduction": "Paghahanda sa sakuna, pagtugon sa emergency, pagbabawas ng panganib",
    "Distribution of fishing gear and equipment": "Pamamahagi ng kagamitan sa pangingisda",
    "Distribution of livestock (swine, goats, poultry) to qualified farmers": "Pamamahagi ng mga hayop (baboy, kambing, manok) sa mga kwalipikadong magsasaka",
    "Distribution of organic and heirloom seeds": "Pamamahagi ng mga organiko at heirloom na binhi",
    "Duly accomplished Application Form": "Wastong napunang Application Form",
    "Duly accomplished Parental Consent or Parental Advice": "Wastong napunang Pahintulot ng Magulang o Payo ng Magulang",
    "Dump trucks, backhoes, graders, and construction equipment": "Mga dump truck, backhoe, grader, at kagamitan sa konstruksyon",
    "Early childhood care and development program": "Programa ng maagang pangangalaga at pagpapaunlad ng bata",
    "Emergency response and disaster preparedness programs.": "Mga programa ng pagtugon sa emergency at paghahanda sa sakuna.",
    "Employment Facilitation (EF)": "Pagpapadali ng Trabaho (EF)",
    "Farm registration, certifications, and agricultural programs for Solano farmers": "Pagpaparehistro ng bukid, mga sertipikasyon, at mga programang agrikultural para sa mga magsasaka ng Solano",
    "Financial aid for hospitalization, medicines, laboratory tests, and medical procedures.": "Tulong pinansyal para sa ospitalisasyon, gamot, mga pagsusuri sa laboratoryo, at mga medikal na pamamaraan.",
    "Financial standing for fiscal year 2023": "Kalagayang pinansyal para sa taong piskal 2023",
    "For newly constructed buildings, improvements, or newly discovered properties.": "Para sa mga bagong itinayong gusali, pagpapabuti, o bagong natuklasang ari-arian.",
    "For Timely Registration (Within 15/30 Days)": "Para sa Napapanahong Pagpaparehistro (Sa Loob ng 15/30 Araw)",
    "Gross sales declaration": "Deklarasyon ng kabuuang benta",
    "Group activities to develop social skills and interaction.": "Mga aktibidad ng grupo upang mapaunlad ang mga kasanayan sa pakikisalamuha.",
    "IEC campaigns on RA 9003 (Solid Waste Management) and RA 9275 (Clean Water Act).": "Mga kampanya ng IEC sa RA 9003 (Pamamahala ng Solidong Basura) at RA 9275 (Clean Water Act).",
    "Issuance of Equipment": "Pagbibigay ng Kagamitan",
    "Issuance of Fuel": "Pagbibigay ng Gasolina",
    "Issuance of Locational Clearance": "Pagbibigay ng Locational Clearance",
    "Issuance of Market Clearance/Certification": "Pagbibigay ng Market Clearance/Sertipikasyon",
    "Issuance of Mayor's Clearance": "Pagbibigay ng Clearance ng Alkalde",
    "Issuance of Mayor's Clearance/Permit": "Pagbibigay ng Clearance/Permiso ng Alkalde",
    "Issuance of Purchase Order (PO)": "Pagbibigay ng Purchase Order (PO)",
    "Issuance of Semi-Expendable": "Pagbibigay ng Semi-Expendable",
    "Issuance of Supplies": "Pagbibigay ng mga Suplay",
    "Issuance of Zoning Clearance/Certification": "Pagbibigay ng Zoning Clearance/Sertipikasyon",
    "Issuance of cedula for individuals and corporations": "Pagbibigay ng cedula para sa mga indibidwal at korporasyon",
    "Linkage to organic markets and buyers": "Koneksyon sa mga organikong pamilihan at mamimili",
    "List of all properties declared under a person's name.": "Listahan ng lahat ng ari-ariang idineklara sa pangalan ng isang tao.",
    "List of Machineries with Specifications": "Listahan ng mga Makinarya na may Detalye",
    "Loan facilitation for rice production through partner institutions": "Pagpapadali ng pautang para sa produksyon ng bigas sa pamamagitan ng mga kasosyong institusyon",
    "Location Sketch/Map": "Sketch/Mapa ng Lokasyon",
    "Major development projects serving the community": "Mga pangunahing proyekto ng pagpapaunlad na nagsisilbi sa komunidad",
    "Maximum 72% (36 months)": "Pinakamataas na 72% (36 buwan)",
    "Medical Certificate (for sex correction)": "Medical Certificate (para sa pagwawasto ng kasarian)",
    "Medical Certificate (if attended by physician)": "Medical Certificate (kung dinaluhan ng doktor)",
    "Microenterprise Development (MD)": "Pagpapaunlad ng Microenterprise (MD)",
    "Negative Certification from PSA": "Negatibong Sertipikasyon mula sa PSA",
    "Newspaper Publication": "Publikasyon sa Pahayagan",
    "Newspaper Publication (3 consecutive weeks)": "Publikasyon sa Pahayagan (3 magkakasunod na linggo)",
    "Nutritious snacks and meals during day care hours.": "Masustansyang meryenda at pagkain sa oras ng day care.",
    "Parental Advice (ages 22-24)": "Payo ng Magulang (edad 22-24)",
    "Parental Consent (ages 18-21)": "Pahintulot ng Magulang (edad 18-21)",
    "Payroll computation sheet": "Sheet ng pagkalkula ng payroll",
    "Payroll cut-off is every 10th and 25th of the month": "Ang cut-off ng payroll ay tuwing ika-10 at ika-25 ng buwan",
    "Petition Form": "Form ng Petisyon",
    "Posting of processed ObR at the logbook": "Pag-post ng naprosesong ObR sa logbook",
    "Pre-audited DV": "Na-pre-audit na DV",
    "Preparation and Issuance of Checks": "Paghahanda at Pagbibigay ng mga Tseke",
    "Preparation of JEV and Financial Statements": "Paghahanda ng JEV at mga Pahayag Pinansyal",
    "Preparation of Payroll": "Paghahanda ng Payroll",
    "Preparation of Transmittal": "Paghahanda ng Transmittal",
    "Primary and Elementary Schools": "Mga Primarya at Elementaryang Paaralan",
    "Procurement of Common-Use Supplies": "Pagkuha ng mga Karaniwang Suplay",
    "Proof of Acquisition/Invoice": "Patunay ng Pagkuha/Invoice",
    "Proof of Income (if employed)": "Patunay ng Kita (kung may trabaho)",
    "Proof of residence in Solano": "Patunay ng paninirahan sa Solano",
    "RA 9048 - Clerical Error Correction": "RA 9048 - Pagwawasto ng Klerikal na Error",
    "Recording and storage of supplies": "Pagtatala at pag-iimbak ng mga suplay",
    "Registration in the Fisherfolk Registry (FishR)": "Pagpaparehistro sa Fisherfolk Registry (FishR)",
    "Registration of livestock for monitoring and program eligibility": "Pagpaparehistro ng livestock para sa pagsubaybay at pagiging karapat-dapat sa programa",
    "Regular health check-ups and growth monitoring.": "Regular na pagsusuri sa kalusugan at pagsubaybay sa paglago.",
    "Regular maintenance and repair coordination": "Regular na pagpapanatili at koordinasyon ng pagkukumpuni",
    "Regular weighing and height measurement to track progress.": "Regular na pagtimbang at pagsukat ng taas upang subaybayan ang pag-unlad.",
    "Rehabilitation / Major Repair of Flood Control Structure": "Rehabilitasyon / Malaking Pagkukumpuni ng Istruktura ng Flood Control",
    "Releasing of MTOF": "Paglabas ng MTOF",
    "Report/referral received at MSWDO": "Ulat/referral na natanggap sa MSWDO",
    "Reporting of utility issues and concerns": "Pag-uulat ng mga isyu at alalahanin sa utilidad",
    "Resolutions passed by the Sangguniang Bayan expressing the will or opinion of the legislative body on various matters.": "Mga resolusyong ipinasa ng Sangguniang Bayan na nagpapahayag ng kalooban o opinyon ng lehislatura sa iba't ibang usapin.",
    "Segregation and recycling initiatives": "Mga inisyatiba sa paghihiwalay at pag-recycle",
    "Sex/DOB Correction (RA 10172)": "Pagwawasto ng Kasarian/Petsa ng Kapanganakan (RA 10172)",
    "Signatures of at least two (2) witnesses": "Mga lagda ng hindi bababa sa dalawang (2) saksi",
    "Sketch of Farm Location": "Sketch ng Lokasyon ng Bukid",
    "Submission to PS-DBM for common-use supplies": "Pagsusumite sa PS-DBM para sa mga karaniwang suplay",
    "Submission to Sangguniang Bayan": "Pagsusumite sa Sangguniang Bayan",
    "Subsidized fertilizer for corn production": "Subsidyadong pataba para sa produksyon ng mais",
    "Supplies issuance follows FIFO method": "Ang pagbibigay ng suplay ay sumusunod sa FIFO method",
    "Timely Registration (Within 30 days)": "Napapanahong Pagpaparehistro (Sa loob ng 30 araw)",
    "Training and resources for disaster readiness": "Pagsasanay at mga mapagkukunan para sa paghahanda sa sakuna",
    "Training on fish culture and pond management": "Pagsasanay sa pag-aalaga ng isda at pamamahala ng palaisdaan",
    "Training on modern rice farming techniques and technologies": "Pagsasanay sa mga modernong teknik at teknolohiya sa pagsasaka ng bigas",
    "Training on organic production methods and composting": "Pagsasanay sa mga pamamaraan ng organikong produksyon at pag-compost",
    "Training on proper animal husbandry and management": "Pagsasanay sa wastong pag-aalaga at pamamahala ng mga hayop",
    "Tree planting and reforestation programs to establish forest cover and preserve biodiversity.": "Mga programa ng pagtatanim ng puno at reforestation upang magtatag ng takip-gubat at mapanatili ang biodiversity.",
    "Two (2) documentary evidences": "Dalawang (2) dokumentaryong ebidensya",
    "Vaccination, deworming, and veterinary consultations": "Bakuna, pagpapapurga, at konsultasyon sa beterinaryo",
    "Vehicle registration (OR/CR)": "Pagpaparehistro ng sasakyan (OR/CR)",
    "Vocational and life skills training for self-sufficiency.": "Pagsasanay sa bokasyonal at kasanayan sa buhay para sa sariling kasapatan.",
    "Bulk processing may take longer": "Ang maramihang pagproseso ay maaaring mas matagal",
    "Appraisal and valuation of real properties for taxation purposes": "Pagtatasa at pagpapahalaga ng mga tunay na ari-arian para sa layunin ng pagbubuwis",
    "Budget preparation, appropriations, fiscal management": "Paghahanda ng badyet, mga appropriasyon, pamamahala ng piskal",
    "Building permits, construction permits, and engineering services": "Mga permiso sa pagtatayo, mga permiso sa konstruksyon, at mga serbisyo sa inhinyeriya",
    "Certificate of occupancy for completed buildings": "Sertipiko ng paninirahan para sa mga natapos na gusali",
    "Agriculture, Aquaculture & Food Security, Overseas Filipino Workers Affairs": "Agrikultura, Akwakultura at Seguridad sa Pagkain, Mga Usapin ng mga Overseas Filipino Worker",
    "Education, Science & Technology, Transportation, Commerce, Trade & Industry": "Edukasyon, Agham at Teknolohiya, Transportasyon, Komersyo, Kalakalan at Industriya",
    "Games, Entertainment & Amusement, Internal Affairs": "Mga Laro, Libangan at Aliwan, Panloob na Usapin",
    "Health, Education, Welfare": "Kalusugan, Edukasyon, Kagalingan",
    "Legal, Good Governance, Justice, Human Rights, Environmental Management": "Legal, Mabuting Pamamahala, Hustisya, Karapatang Pantao, Pamamahala ng Kapaligiran",
    "Assessed Value Computation": "Pagkalkula ng Tinasang Halaga",
    "Actual Use of Land": "Aktwal na Gamit ng Lupa",
    "Address / Telephone No.": "Adres / Numero ng Telepono",
    "Administration & Operations": "Administrasyon at Operasyon",
    "Abstract of Quotations and Award": "Abstrak ng mga Quotation at Award",
    "Adverse Claim": "Adverse Claim",
    "Affidavit of Acknowledgment/Admission of Paternity (if illegitimate)": "Sinumpaang Salaysay ng Pagkilala/Pag-amin ng Pagka-ama (kung illegitimate)",
    "Affidavit of Closure": "Sinumpaang Salaysay ng Pagsasara",
    "Affidavit of Publication": "Sinumpaang Salaysay ng Publikasyon",
    "Annotation of Court Order": "Anotasyon ng Utos ng Hukuman",
    "Application Form for Zoning Certification": "Application Form para sa Zoning Certification",
    "ARP No. (Assessment Roll)": "ARP No. (Assessment Roll)",
    "As assessed": "Ayon sa pagtatasa",
    "Based on Revenue": "Batay sa Kita",
    "Based on quantity": "Batay sa dami",
    "Based on volume": "Batay sa dami",
    "Based on weight": "Batay sa timbang",
    "Basic Fee": "Pangunahing Bayad",
    "Best option for savings": "Pinakamahusay na opsyon para sa ipon",
    "BIR Registration": "BIR Registration",
    "Brand and Model": "Tatak at Modelo",
    "Break": "Pahinga",
    "Budget Message of the Punong Barangay": "Mensahe ng Badyet ng Punong Barangay",
    "Budget of Expenditures and Sources of Financing": "Badyet ng mga Gastusin at mga Pinagmulan ng Pananalapi",
    "Cancellation of Mortgage": "Pagkansela ng Mortgage",
    "Canvass/Request for Quotation from suppliers": "Canvass/Kahilingan ng Quotation mula sa mga supplier",
    "Capacity/Horse Power": "Kapasidad/Horse Power",
    "Capacity/Specs": "Kapasidad/Detalye",
    "CDA Registration (for cooperatives)": "CDA Registration (para sa mga kooperatiba)",
    "Centers": "Mga Sentro",
    "Contracting Parties": "Mga Partido sa Kontrata",
    "Court Decree of Annulment/Nullity": "Decree ng Hukuman ng Annulment/Nullity",
    "Date Acquired/Installed": "Petsa ng Pagkuha/Pag-install",
    "Date Constructed/Completed": "Petsa ng Pagtatayo/Pagkumpleto",
    "Death Registration": "Pagpaparehistro ng Pagkamatay",
    "Death Registration (Timely)": "Pagpaparehistro ng Pagkamatay (Napapanahon)",
    "Debt Service": "Serbisyo sa Utang",
    "Discount/Penalty": "Diskwento/Multa",
    "Disease Surveillance": "Pagsubaybay sa Sakit",
    "Driver": "Driver",
    "Drivers Pool": "Pool ng mga Driver",
    "Drivers and Operators": "Mga Driver at Operator",
    "Embalmer": "Embalmer",
    "Embalmer's Certification": "Sertipikasyon ng Embalmer",
    "Estimated Economic Life": "Tinatayang Buhay Pang-ekonomiya",
    "Electricity": "Kuryente",
    "Informant/Family": "Nagpapaalam/Pamilya",
    "Legitimation Annotation": "Anotasyon ng Lehitimasyon",
    "Lis Pendens": "Lis Pendens",
    "Mortgage Annotation": "Anotasyon ng Mortgage",
    "ObR with assigned account code": "ObR na may nakatalagang account code",
    "OCT/TCT/CLOA No.": "OCT/TCT/CLOA No.",
    "Once the Largest": "Dating Pinakamalaki",
    "Spouse/Relative": "Asawa/Kamag-anak",
    "Taxable/Exempt Status": "Katayuang Buwisable/Exempt",
    "10% Discount": "10% Diskwento",
    "2% per month": "2% bawat buwan",
    "Ilocanos arrived": "Dumating ang mga Ilocano",
    "Higher Educational Institutions": "Mga Institusyon ng Mas Mataas na Edukasyon",
    "Secondary Schools": "Mga Sekundaryang Paaralan",
    "Rural Health Units": "Mga Rural Health Unit",
    "Birth Registration": "Pagpaparehistro ng Kapanganakan",
    "Birth/Death Registration": "Pagpaparehistro ng Kapanganakan/Pagkamatay",
    "Marriage Registration": "Pagpaparehistro ng Kasal",
    "Timely Registration": "Napapanahong Pagpaparehistro",
    "Late Registration": "Huling Pagpaparehistro",
    "Delayed Registration": "Naantalang Pagpaparehistro",
    "Brgy. Clearance & Zoning Clearance": "Brgy. Clearance at Zoning Clearance",
    "SEF Budget": "Badyet ng SEF",
    "Total Expenditures": "Kabuuang Gastusin",
    "Total Income": "Kabuuang Kita",
    "Jan 1 - Jan 20": "Ene 1 - Ene 20",
    "FY 2025 quarterly financial performance": "Quarterly na pagganap pinansyal ng FY 2025",
    "DPWH Infrastructure Projects in Solano": "Mga Proyekto ng Imprastraktura ng DPWH sa Solano",
    "DPWH Transparency Portal": "DPWH Transparency Portal",
    "DTI Cities and Municipalities Competitiveness Index (CMCI)": "DTI Cities and Municipalities Competitiveness Index (CMCI)",
    "FCDS Package 5 - Magat River Flood Control": "FCDS Package 5 - Flood Control ng Ilog Magat",
    "3-Day Submission to SP": "3-Araw na Pagsusumite sa SP",
    "10-Day Mayor's Approval": "10-Araw na Pag-apruba ng Alkalde",
    "60-day review for appropriation ordinances; 30-day review for others": "60-araw na pagsusuri para sa mga ordinansa ng appropriasyon; 30-araw na pagsusuri para sa iba",
    "Flowchart for Legislative Proposal": "Flowchart para sa Panukalang Lehislatibo",
    "Initial response time: 1 hour 35 minutes": "Paunang oras ng pagtugon: 1 oras 35 minuto",
    "Initial response time: 50 minutes": "Paunang oras ng pagtugon: 50 minuto",
    "BPLS / VMO / SBO": "BPLS / VMO / SBO",
    "Ambulance Driver/EMT": "Driver ng Ambulansya/EMT",
    "Collection Officer": "Opisyal ng Koleksyon",
    "Engineering Aide": "Katulong sa Inhinyeriya",
    "Heavy Equipment Operator": "Operator ng Mabigat na Kagamitan",
    "Light Vehicle Driver": "Driver ng Magaan na Sasakyan",
    "Dump Truck Driver": "Driver ng Dump Truck",
    "Service Vehicle (Van)": "Sasakyang Panserbisyo (Van)",
    "PhilGEPS Registration": "PhilGEPS Registration",
    "Referring website or source": "Pinanggalingang website o pinagmulan",
    "Source: Sumbong sa Pangulo": "Pinagmulan: Sumbong sa Pangulo",
    "2 Tracks": "2 Track",
    "2 sets - Bill of Materials": "2 set - Bill of Materials",
    "2 sets - Design Analysis": "2 set - Design Analysis",
    "5 sets - Specifications": "5 set - Specifications",
    "1x1 ID photo (2 copies)": "1x1 ID photo (2 kopya)",
    "1x1 ID photos (4 copies each)": "1x1 ID photo (tig-4 na kopya)",
    "1x1 or 2x2 ID photo (2 copies)": "1x1 o 2x2 ID photo (2 kopya)",
    "Backhoe, Grader, Roller": "Backhoe, Grader, Roller",
    "Various KVA": "Iba't ibang KVA",
    "2024 Census": "2024 Senso",
    "Trade &amp; Commerce": "Kalakalan at Komersyo",
    "Barangay": "Barangay",
    "Contents": "Mga Nilalaman",
    "Quarterly": "Quarterly",
    "React": "React",
    "Ongoing": "Kasalukuyan",
    "Completed": "Natapos",
    "Pending": "Nakabinbin",
    "Approved": "Naaprubahan",
    "Denied": "Tinanggihan",
    "Processing": "Pinoproseso",
    "Received": "Natanggap",
    "Submitted": "Naisumite",
    "Verified": "Na-verify",
    "Assessed": "Natasa",
    "Paid": "Nabayaran",
    "Released": "Nailabas",
    "Issued": "Naibigay",
    "Filed": "Naihain",
    "Reviewed": "Nasuri",
    "Evaluated": "Na-evaluate",
    "Inspected": "Na-inspeksyon",
    "Endorsed": "Na-endorse",
    "Certified": "Nasertipikahan",
    "Registered": "Nairehistro",
    "Renewed": "Na-renew",
    "Amended": "Na-amyenda",
    "Cancelled": "Nakansela",
    "Requested": "Hiniling",
    "Resolved": "Nalutas",
    "Closed": "Sarado",
    "Open": "Bukas",
    "Active": "Aktibo",
    "Inactive": "Hindi Aktibo",
    "Valid": "Balido",
    "Invalid": "Hindi Balido",
    "Expired": "Nag-expire",
    "Free": "Libre",
    "None": "Wala",
    "Yes": "Oo",
    "No": "Hindi",
    "Availability": "Pagkakaroon",
    "Certifications": "Mga Sertipikasyon",
    "Age-appropriate educational activities and learning materials.": "Mga aktibidad na pang-edukasyon na angkop sa edad at mga materyales sa pagkatuto.",
    "Assigned Driver": "Nakatalagang Driver",
    "Assigned Operator": "Nakatalagang Operator",
    "Authorized driver assignment": "Awtorisadong pagtatalaga ng driver",
    "Consolidated PRs, APP": "Pinagsama-samang mga PR, APP",
    "Coordination with utility providers": "Koordinasyon sa mga tagapagbigay ng utilidad",
    "Corn Seeds Distribution": "Pamamahagi ng mga Binhi ng Mais",
    "Crop Insurance (PCIC)": "Crop Insurance (PCIC)",
    "PCIC insurance coverage for corn crops": "Saklaw ng seguro ng PCIC para sa mga pananim na mais",
    "SEEDO - Slaughterhouse": "SEEDO - Katayan",
    "SEEDO Slaughterhouse, Solano, Nueva Vizcaya": "SEEDO Katayan, Solano, Nueva Vizcaya",
    "SEEDO – Slaughterhouse": "SEEDO – Katayan",
    "Bintawan Road, Brgy. Quezon": "Bintawan Road, Brgy. Quezon",
    "Magat River, Bagahabag Section, Solano, Nueva Vizcaya": "Ilog Magat, Seksyon ng Bagahabag, Solano, Nueva Vizcaya",
    "Solano, Nueva Vizcaya 3708": "Solano, Nueva Vizcaya 3708",
}

# ============================================================
# ILOCANO PASS 2 - Build from Filipino with Ilocano equivalents
# ============================================================

def build_ilo_from_fil(fil_dict):
    """Build Ilocano translations using Filipino as reference + Ilocano-specific overrides."""
    # Core Ilocano word substitutions from Filipino
    fil_to_ilo = {
        # Time
        'araw': 'aldaw', 'Araw': 'Aldaw',
        'oras': 'oras', 'minuto': 'minuto',
        'linggo': 'lawas', 'buwan': 'bulan',
        'taon': 'tawen', 'Taon': 'Tawen',
        # Months
        'Enero': 'Enero', 'Pebrero': 'Pebrero',
        'Marso': 'Marso', 'Hunyo': 'Hunio',
        'Setyembre': 'Septiembre', 'Disyembre': 'Disiembre',
        # Days
        'Lunes': 'Lunes', 'Biyernes': 'Biernes',
        'Lun-Biy': 'Lun-Biy',
        # Common words
        'mga': 'dagiti', 'Mga': 'Dagiti',
        'ang': 'ti', 'Ang': 'Ti',
        'ng': 'ti', 'sa': 'iti',
        'at': 'ken', 'o': 'wenno',
        'para': 'para', 'mula': 'manipud',
        'kung': 'no', 'Kung': 'No',
        'hindi': 'saan', 'Hindi': 'Saan',
        'wala': 'awan', 'Wala': 'Awan', 'Walang': 'Awan ti',
        'oo': 'wen', 'Oo': 'Wen',
        'libre': 'libre', 'Libre': 'Libre',
        # Government
        'Munisipyo': 'Munisipalidad',
        'Alkalde': 'Mayor', 'alkalde': 'mayor',
        'Opisina': 'Opisina', 'opisina': 'opisina',
        'Kagawaran': 'Departamento',
        'Ingat-Yaman': 'Tesorero',
        'Tagapagtasa': 'Assessor',
        'Inhinyeriya': 'Inhinyeria', 'Inhinyero': 'Inhinyero',
        'Pagpaplano': 'Panagplano',
        'Agrikultura': 'Agrikultura',
        'Kalusugan': 'Salun-at',
        'Kapakanan': 'Pakasaritaan',
        # Services
        'Serbisyo': 'Serbisio', 'serbisyo': 'serbisio',
        'Serbisyong': 'Serbisio a',
        'Pagproseso': 'Panagproseso', 'pagproseso': 'panagproseso',
        'Pagbabayad': 'Panagbayad', 'pagbabayad': 'panagbayad',
        'Pagbibigay': 'Panagipaay', 'pagbibigay': 'panagipaay',
        'Pagpaparehistro': 'Panagparehistro', 'pagpaparehistro': 'panagparehistro',
        'Pagsubaybay': 'Panagmonitor', 'pagsubaybay': 'panagmonitor',
        'Pagpapanatili': 'Panagtaginayon',
        'Paghahanda': 'Panagisagana', 'paghahanda': 'panagisagana',
        'Pagsusuri': 'Panagrepaso', 'pagsusuri': 'panagrepaso',
        'Pagsusumite': 'Panagisumite', 'pagsusumite': 'panagisumite',
        'Pagtatasa': 'Panagpatasa', 'pagtatasa': 'panagpatasa',
        'Pagwawasto': 'Panagkorehir', 'pagwawasto': 'panagkorehir',
        'Pagkansela': 'Panagkansela',
        'Pamamahagi': 'Panagipakat', 'pamamahagi': 'panagipakat',
        'Pamamahala': 'Panagtaripato', 'pamamahala': 'panagtaripato',
        'Pagsasanay': 'Panagsanay', 'pagsasanay': 'panagsanay',
        'Pagpapatupad': 'Panangipakat',
        'Pagpapaunlad': 'Panagrang-ay', 'pagpapaunlad': 'panagrang-ay',
        'Pagpapadali': 'Panagpasimple',
        'Pagkuha': 'Panagala', 'pagkuha': 'panagala',
        'Pagkatay': 'Panagparti', 'pagkatay': 'panagparti',
        'Paglabas': 'Panagiruar', 'paglabas': 'panagiruar',
        'Pagtanggap': 'Panagawat', 'pagtanggap': 'panagawat',
        'Pag-upa': 'Panagabang', 'pag-upa': 'panagabang',
        'Pag-renew': 'Panagpabaro', 'pag-renew': 'panagpabaro',
        'Pag-apruba': 'Panag-apruba', 'pag-apruba': 'panag-apruba',
        'Pag-post': 'Panag-post', 'pag-post': 'panag-post',
        # Documents
        'Dokumento': 'Dokumento', 'dokumento': 'dokumento',
        'Sertipiko': 'Sertipiko', 'sertipiko': 'sertipiko',
        'Sertipikasyon': 'Sertipikasion', 'sertipikasyon': 'sertipikasion',
        'Permiso': 'Permiso', 'permiso': 'permiso',
        'Lisensya': 'Lisensia', 'lisensya': 'lisensia',
        'Resolusyon': 'Resolusion', 'resolusyon': 'resolusion',
        'Ordinansa': 'Ordinansa', 'ordinansa': 'ordinansa',
        'Rekord': 'Rekord', 'rekord': 'rekord',
        'Ulat': 'Report', 'ulat': 'report',
        'Badyet': 'Badyet', 'badyet': 'badyet',
        'Bayad': 'Bayad', 'bayad': 'bayad',
        'Gastusin': 'Gastos', 'gastusin': 'gastos',
        'Kita': 'Sapul', 'kita': 'sapul',
        'Buwis': 'Buwis', 'buwis': 'buwis',
        # People
        'Magsasaka': 'Mannalon', 'magsasaka': 'mannalon',
        'Mangingisda': 'Mangngalap', 'mangingisda': 'mangngalap',
        'Kliyente': 'Kliente', 'kliyente': 'kliente',
        'Benepisyaryo': 'Benepisario', 'benepisyaryo': 'benepisario',
        'May-ari': 'Akinkukua', 'may-ari': 'akinkukua',
        'Kamag-anak': 'Kabagian', 'kamag-anak': 'kabagian',
        'Kinatawan': 'Pannakabagi', 'kinatawan': 'pannakabagi',
        'Mamamayan': 'Umili', 'mamamayan': 'umili',
        'Matatandang': 'Nataengan a',
        # Nouns
        'Impormasyon': 'Impormasion', 'impormasyon': 'impormasion',
        'Kahilingan': 'Kiddaw', 'kahilingan': 'kiddaw',
        'Kinakailangan': 'Kasapulan', 'kinakailangan': 'kasapulan',
        'Kinakailangang': 'Kasapulan a',
        'Kalagayan': 'Kasasaad',
        'Katayuan': 'Kasasaad', 'katayuan': 'kasasaad',
        'Lokasyon': 'Lokasion', 'lokasyon': 'lokasion',
        'Programa': 'Programa', 'programa': 'programa',
        'Proyekto': 'Proyekto', 'proyekto': 'proyekto',
        'Negosyo': 'Negosio', 'negosyo': 'negosio',
        'Trabaho': 'Trabaho', 'trabaho': 'trabaho',
        'Pamilihan': 'Tiendaan', 'pamilihan': 'tiendaan',
        'Katayan': 'Pagpartian', 'katayan': 'pagpartian',
        'Ari-arian': 'Kukua', 'ari-arian': 'kukua',
        'Lupa': 'Daga', 'lupa': 'daga',
        'Gusali': 'Pasdek', 'gusali': 'pasdek',
        'Sasakyan': 'Lugan', 'sasakyan': 'lugan',
        'Kagamitan': 'Ramit', 'kagamitan': 'ramit',
        'Suplay': 'Suplay', 'suplay': 'suplay',
        'Paaralan': 'Eskuelaan', 'paaralan': 'eskuelaan',
        'Paaralang': 'Eskuelaan a',
        'Kapaligiran': 'Aglawlaw', 'kapaligiran': 'aglawlaw',
        'Komunidad': 'Komunidad', 'komunidad': 'komunidad',
        'Sakuna': 'Didigra', 'sakuna': 'didigra',
        'Kalamidad': 'Kalamidad', 'kalamidad': 'kalamidad',
        'Tubig': 'Danum', 'tubig': 'danum',
        'Kuryente': 'Koriente', 'kuryente': 'koriente',
        'Basura': 'Basura', 'basura': 'basura',
        'Pagkain': 'Makan', 'pagkain': 'makan',
        'Balita': 'Damag', 'balita': 'damag',
        'Pahinga': 'Inana', 'pahinga': 'inana',
        # Adjectives
        'Bagong': 'Baro a', 'bagong': 'baro a',
        'Bago': 'Baro', 'bago': 'baro',
        'Mahalagang': 'Napateg a', 'mahalagang': 'napateg a',
        'Mahalaga': 'Napateg', 'mahalaga': 'napateg',
        'Pangunahing': 'Kangrunaan a', 'pangunahing': 'kangrunaan a',
        'Pangkalahatang': 'Sapasap a',
        'Kasalukuyang': 'Agdama a',
        'Kasalukuyan': 'Agtultuloy',
        'Natapos': 'Nalpas',
        'Nakabinbin': 'Agur-uray',
        'Naaprubahan': 'Naaprubaran',
        'Tinanggihan': 'Naidian',
        'Pinoproseso': 'Agproproseso',
        'Natanggap': 'Naawat',
        'Naisumite': 'Naisumite',
        'Natasa': 'Napatasan',
        'Nabayaran': 'Nabayadan',
        'Nailabas': 'Nairuar',
        'Naibigay': 'Naipaay',
        'Naihain': 'Naipila',
        'Nasuri': 'Narepaso',
        'Nasertipikahan': 'Nasertipikaran',
        'Nairehistro': 'Naiparehistro',
        'Nakansela': 'Nakansela',
        'Hiniling': 'Nakiddaw',
        'Nalutas': 'Narisut',
        'Sarado': 'Naserraan',
        'Bukas': 'Nakalukat',
        'Aktibo': 'Aktibo',
        'Balido': 'Balido',
        'Subsidyado': 'Subsidyado',
        # Verbs
        'Isumite': 'Isumite', 'isumite': 'isumite',
        'Tingnan': 'Kitaen', 'tingnan': 'kitaen',
        'Suriin': 'Repasuen', 'suriin': 'repasuen',
        'Pumunta': 'Mapan', 'pumunta': 'mapan',
        'Bumalik': 'Agsubli', 'bumalik': 'agsubli',
        'Maghintay': 'Aguray', 'maghintay': 'aguray',
        'Magbayad': 'Agbayad', 'magbayad': 'agbayad',
        'Punan': 'Punuan', 'punan': 'punuan',
        'Pumirma': 'Agpirma', 'pumirma': 'agpirma',
        'Tanggapin': 'Awaten', 'tanggapin': 'awaten',
        'Kunin': 'Alaen', 'kunin': 'alaen',
        'Ipakita': 'Ipakita', 'ipakita': 'ipakita',
        'Piliin': 'Pilien', 'piliin': 'pilien',
        'Manatiling': 'Agtalinaed a',
    }
    
    ilo = {}
    for en_key, fil_val in fil_dict.items():
        ilo_val = fil_val
        # Apply word substitutions (longest first to avoid partial matches)
        for fil_word in sorted(fil_to_ilo.keys(), key=len, reverse=True):
            ilo_word = fil_to_ilo[fil_word]
            # Use word boundary matching
            ilo_val = re.sub(r'\b' + re.escape(fil_word) + r'\b', ilo_word, ilo_val)
        ilo[en_key] = ilo_val
    return ilo

# ============================================================
# MAIN EXECUTION
# ============================================================

def main():
    print("=" * 60)
    print("PASS 2: TRANSLATING REMAINING KEYS")
    print("=" * 60)

    with open(TRANSLATIONS_JS, 'r') as f:
        content = f.read()

    en, en_order = extract_lang_dict(content, 'en')
    fil, fil_order = extract_lang_dict(content, 'fil')
    ilo, ilo_order = extract_lang_dict(content, 'ilo')

    # Merge all Filipino dictionaries
    all_fil = {}
    all_fil.update(PASS2_FIL)
    all_fil.update(PASS2_FIL_2)
    all_fil.update(PASS2_FIL_3)
    all_fil.update(PASS2_FIL_4)

    # Build Ilocano from Filipino
    all_ilo = build_ilo_from_fil(all_fil)

    # Count untranslated before
    before_fil = sum(1 for k in en if fil.get(k) == en[k])
    before_ilo = sum(1 for k in en if ilo.get(k) == en[k])
    print(f"Before - FIL untranslated: {before_fil}, ILO untranslated: {before_ilo}")

    # Apply translations
    fil_count = 0
    ilo_count = 0
    for key in en:
        en_val = en[key]
        
        # Filipino
        if fil.get(key) == en_val and en_val in all_fil:
            new_val = all_fil[en_val]
            if new_val != en_val:
                fil[key] = new_val
                fil_count += 1
        
        # Ilocano
        if ilo.get(key) == en_val and en_val in all_ilo:
            new_val = all_ilo[en_val]
            if new_val != en_val:
                ilo[key] = new_val
                ilo_count += 1

    print(f"Applied - FIL: {fil_count}, ILO: {ilo_count}")

    # Rebuild translations.js
    def build_lang_block(lang_dict, order, indent='        '):
        lines = []
        for i, key in enumerate(order):
            val = lang_dict.get(key, '')
            escaped_val = val.replace('\\', '\\\\').replace('"', '\\"')
            comma = ',' if i < len(order) - 1 else ''
            lines.append(f'{indent}"{key}": "{escaped_val}"{comma}')
        return '\n'.join(lines)

    def replace_lang_block(content, lang, lang_dict, order):
        lines = content.split('\n')
        start_idx = None
        end_idx = None
        brace_depth = 0
        for i, line in enumerate(lines):
            if start_idx is None:
                if re.match(rf'\s*{lang}:\s*\{{', line):
                    start_idx = i
                    brace_depth = 1
                    continue
            else:
                brace_depth += line.count('{') - line.count('}')
                if brace_depth <= 0:
                    end_idx = i
                    break
        if start_idx is not None and end_idx is not None:
            new_lines = lines[:start_idx + 1]
            new_lines.append(build_lang_block(lang_dict, order))
            new_lines.extend(lines[end_idx:])
            return '\n'.join(new_lines)
        return content

    print("Rebuilding translations.js...")
    content = replace_lang_block(content, 'fil', fil, fil_order)
    content = replace_lang_block(content, 'ilo', ilo, ilo_order)

    with open(TRANSLATIONS_JS, 'w') as f:
        f.write(content)

    # Verify
    with open(TRANSLATIONS_JS, 'r') as f:
        verify = f.read()

    v_en, _ = extract_lang_dict(verify, 'en')
    v_fil, _ = extract_lang_dict(verify, 'fil')
    v_ilo, _ = extract_lang_dict(verify, 'ilo')

    after_fil = sum(1 for k in v_en if v_fil.get(k) == v_en[k])
    after_ilo = sum(1 for k in v_en if v_ilo.get(k) == v_en[k])
    print(f"\nAfter - FIL untranslated: {after_fil}, ILO untranslated: {after_ilo}")
    print(f"FIL: {len(v_en)} keys, {len(v_en) - after_fil} translated ({(len(v_en) - after_fil) / len(v_en) * 100:.1f}%)")
    print(f"ILO: {len(v_en)} keys, {len(v_en) - after_ilo} translated ({(len(v_en) - after_ilo) / len(v_en) * 100:.1f}%)")

    # Show remaining untranslated
    remaining = []
    for k in v_en:
        if v_fil.get(k) == v_en[k]:
            remaining.append((k, v_en[k]))
    
    print(f"\n--- Remaining untranslated (first 30) ---")
    for k, v in remaining[:30]:
        print(f"  {k}: \"{v[:80]}\"")


if __name__ == '__main__':
    main()
